Fix build with Catch2 v3: include catch_interfaces_capture.hpp
Catch::getResultCapture() requires an explicit include of
<catch2/interfaces/catch_interfaces_capture.hpp> in Catch2 v3,
which was not previously included.

tests/sla_print/sla_test_utils.cpp:87:32: error: ‘getResultCapture’ is not a member of ‘Catch’
    m.WriteOBJFile((Catch::getResultCapture().getCurrentTestName() + "_" +
                           ^~~~~~~~~~~~~~~~